version: '3'
services: 
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "9443"
      - "9043"
      - "9080"
    ports: 
      - "9443:9443"
      - "9043:9043"
      - "9080:9080"
    volumes: 
      - ./contrast:/contrast
      - ./tmp:/tmp
      - ./logs:/logs
      - ./deploy:/opt/IBM/WebSphere/AppServer/profiles/AppSrv01/monitoredDeployableApps/servers/server1


